-- USERDETAILS
INSERT INTO USER_DETAILS (USER_ID, TITLE, FIRST_NAME, LAST_NAME, GENDER, STREET, CITY, STATE, POSTCODE) VALUES (1, 'Mr', 'John', 'Doe', 'Male','Wombat street','Sydney','NSW','2000');
INSERT INTO USER_DETAILS (USER_ID, TITLE, FIRST_NAME, LAST_NAME, GENDER, STREET, CITY, STATE, POSTCODE) VALUES (2, 'Mr', 'Kathy', 'Joe', 'Female', 'Roo street','Brisbane','QLD','4000');
